# SPDX-License-Identifier: BSD-2-Clause
# X-SPDX-Copyright-Text: (c) Copyright 2023 Advanced Micro Devices, Inc.

name: "repo_compatibility_check"


on: push

jobs:
  ssa:
    if: vars.INTERNAL_REPO
    runs-on: ubuntu-latest
    steps:
      - name: onload_internal
        uses: actions/checkout@v4
        with:
          path: onload_internal

      - name: Extract simple_sockets_apps branch name
        id: ssa_ref
        run: echo "branch=$(yq -r '.products.simple_sockets_apps.version' < $GITHUB_WORKSPACE/onload_internal/versions.yaml)" >> "$GITHUB_OUTPUT"

      - name: ssa checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/simple_sockets_apps
          ssh-key: ${{ secrets.SIMPLE_SOCKET_APPS_READ_PRIVATE_KEY }}
          path: ssa
          ref: ${{ steps.ssa_ref.outputs.branch }}

      - name: ssa build
        run: |
          cd $GITHUB_WORKSPACE/ssa
          make ONLOAD_TREE=$GITHUB_WORKSPACE/onload_internal -j $(nproc)
