# SPDX-License-Identifier: BSD-2-Clause
# X-SPDX-Copyright-Text: (c) Copyright 2023 Advanced Micro Devices, Inc.

name: "perform_developing_md_build"

on: push

jobs:
  perform_developing_md_build:
    runs-on: ubuntu-latest
    steps:
      - name: onload_internal
        uses: actions/checkout@v4
        with:
          path: onload_internal

      - name: Install Onload Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcap-dev libmnl-dev

      - name: setup Env
        run: |
          echo "$GITHUB_WORKSPACE/onload_internal/scripts" >> $GITHUB_PATH

      - name: mmake buildtrees
        run: |
          cd $GITHUB_WORKSPACE/onload_internal
          mmakebuildtree --driver
          mmakebuildtree --user

      - name: build DEBUG driver
        run: |
          make -C "$(mmaketool --toppath)/build/$(mmaketool --driverbuild)" -j $(nproc)

      - name: build DEBUG user
        run: |
          make -C "$(mmaketool --toppath)/build/$(mmaketool --userbuild)" -j $(nproc)

      - name: build NDEBUG driver
        run: |
          make -C "$(mmaketool --toppath)/build/$(mmaketool --driverbuild)" -j $(nproc) NDEBUG=1

      - name: build NDEBUG user
        run: |
          make -C "$(mmaketool --toppath)/build/$(mmaketool --userbuild)" -j $(nproc) NDEBUG=1

      - name: NEW Make build check
        run: |
          rm -rf "$(mmaketool --toppath)/build"
          make -C "$(mmaketool --toppath)" -j $(nproc)
